services:
  weather-mcp:
    image: ghcr.io/jetski-sh/weather-mcp-python:main
    ports:
      - 8000:8000
  dex:
    image: ghcr.io/dexidp/dex:v2.43.1-distroless
    command: ["dex", "serve", "/config.yaml"]
    ports:
      - 5556:5556
      - 5557:5557
    configs:
      - source: config.yaml
        target: /config.yaml
    env_file:
      - .dex.secret.env
  # keycloak:
  #   image: quay.io/keycloak/keycloak:26.3.1
  #   command: ["start-dev"]
  #   ports:
  #     - 8080:8080
  #   environment:
  #     - KEYCLOAK_ADMIN=admin
  #     - KEYCLOAK_ADMIN_PASSWORD=admin

configs:
  config.yaml:
    content: |
      issuer: http://localhost:5556/
      web:
        http: 0.0.0.0:5556
        allowedOrigins: ['*']
      grpc:
        addr: 0.0.0.0:5557
      storage:
        type: sqlite3
      oauth2:
        skipApprovalScreen: true
      connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: {{ .Env.GITHUB_CLIENT_ID }}
          clientSecret: {{ .Env.GITHUB_CLIENT_SECRET }}
          redirectURI: http://localhost:5556/callback
