host: http://localhost:9000/
authorization:
  server: http://localhost:5556/
  serverMetadataProxyEnabled: true
  dynamicClientRegistrationEnabled: true
dexGRPCClient:
  addr: localhost:5557
proxy:
  - path: /weather/mcp
    http:
      url: http://localhost:8000/mcp
