host: http://localhost:9000/
authorization:
  server: http://localhost:5556/
  serverMetadataProxyEnabled: true
  dynamicClientRegistrationEnabled: true
dexGRPCClient:
  addr: localhost:5557
proxy:
  - path: /weather/mcp
    http:
      url: http://localhost:8000/mcp
    webhook:
      url: http://localhost:8080/webhook/proxy/b7dc761d-a488-4186-a40e-4d9831d562dc
