host: http://localhost:9000/
authorization:
  server: http://localhost:5556/
  serverMetadataProxyEnabled: true
  dynamicClientRegistrationEnabled: true
dexGRPCClient:
  addr: localhost:5557
proxy:
  - path: /weather/mcp
    http:
      url: http://localhost:8000/mcp
webhook:
  url: https://webhook.site/ec346a12-0169-4eb9-b885-2176e3340737
