host: http://localhost:9000/
authorization:
  server: http://dex:5556/
  serverMetadataProxyEnabled: true
  dynamicClientRegistrationEnabled: true
dexGRPCClient:
  addr: dex:5557
proxy:
  - path: /who-am-i/mcp
    http:
      url: http://who-am-i:3000/mcp/
    authentication:
      enabled: true
